/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EasyCodeBlock
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var EasyCodeBlock = class extends import_obsidian.Plugin {
  async onload() {
    this.addRibbonIcon("code-glyph", "Easy Code Block", (evt) => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (!view) {
        return;
      }
      const editor = view.editor;
      const selection = editor.getSelection();
      if (selection) {
        const startCursor = editor.getCursor("from");
        editor.replaceSelection("```\n" + selection + "\n```");
        editor.setCursor({
          line: startCursor.line,
          ch: startCursor.ch + 3
        });
      } else {
        const cursor = editor.getCursor();
        editor.replaceRange("```\n```", cursor);
        editor.setCursor({
          line: cursor.line,
          ch: cursor.ch + 3
        });
      }
    });
  }
  onunload() {
  }
};
